### ISSUE TITLE
Spawn Chunks Not Generating (1.20.6)

### ISSUE THREAD

**Issue by DaBomb42** [DavidS-Repo/SkyGridx#3]
No blocks are generating within a 7x7 chunk area around spawn in any dimension. 
using paper-1.20.6-51

I saw your reply to Goreator's post on spigot about a workaround, but it doesn't work now that /sgon is removed. 

In the meantime, I will try it on other versions

**Comment by DavidS-Repo** [comment]
It appears that there's an issue with how spawn chunks are being loaded in the experimental versions of 1.20.6 for Paper. Previously, I had resolved a similar issue by forcibly generating the spawn chunks once when the server first launches, specifically for version 1.20.4. However, it seems that something has changed in the experimental builds for Paper 1.20.6, causing the chunks not to load or not to be detected during loading by the chunk load events.

To temporarily address this, you can revert to the last stable version of Paper for 1.20.4, where the issue was resolved. Launch the server with this version first, ensuring fresh files, which should properly generate the spawn chunks. Afterwards, you can save and switch to the experimental 1.20.6 build of Paper. Note that there may be errors related to Armadillo, as it didn't exist in the earlier version. However, the code should handle this gracefully by choosing alternative items or blocks.

In the meantime, I'll start working on a more permanent solution to prevent this issue from recurring in the future, especially if chunk loading mechanisms are altered again.

**Comment by DavidS-Repo** [comment]
Implemented a fix to delay chunk generation until the server has fully loaded, ensuring that spawn chunks are generated properly. This resolves the issue reported with spawn chunks not generating in versions 1.20.6. The fix prevents generation during server boot, addressing the root cause of the problem. Issue should be resolved now.

The fix is included in this [commit](https://github.com/DavidS-Repo/SkyGridx/commit/e301e229a78f24a9070d4b22661cc4e0187cb14c).

The fixed versions of the jar are available in the [main page](https://github.com/DavidS-Repo/SkyGridx).
[SkyGrid_128x.jar](https://github.com/DavidS-Repo/SkyGridx/blob/main/SkyGrid_128x.jar) is the default available publicly.
[SkyGrid_256x.jar](https://github.com/DavidS-Repo/SkyGridx/blob/main/SkyGrid_256x.jar) has increase overworld generation height to y 256 (harder to run).

**Comment by DaBomb42** [comment]
Wow, I was not expecting a response so soon. Thank you so much for fixing it so quickly! It works flawlessly now

**Comment by CorentinStauder** [comment]
Hello there, I'm on paper 1.20.1 and with the latest plugin version (updated may 17 on spigot) my center chunks are still not generating

**Comment by DavidS-Repo** [comment]
Hello @CorentinStauder,

Thank you for reaching out. I am currently working on enhancing the safety mechanisms for initial spawn chunk generation. Although I have already implemented some measures, I cannot replicate the issue on my own system, making it difficult to diagnose. It appears the issue might be hardware-related or specific to certain configurations. I acknowledge that my earlier implementations did not fully resolve the problem.

In the meantime, you can use the /regen command to regenerate all loaded chunks. To fix the spawn chunks, go to the spawn area and use this command. This should temporarily resolve the issue while I work on a more permanent fix.

Thank you for your patience and understanding.

Best,
David

**Comment by DavidS-Repo** [comment]
Implemented a fix to delay entire plugin initialization until the server has fully loaded, ensuring that spawn chunks are generated properly. To fix you currently broken chunks performed a full reset by deleting all folders except the plugin and world folders, leaving the plugin folder empty with only the plugin, and the world folder with just the datapacks folder and the void datapack inside. Launch the server with the updated jar and it should properly generate the spawn chunks. (if the issue still happening let me know I will implement some other safe measures)


The fixed version of the jar is available in the [main page](https://github.com/DavidS-Repo/SkyGridx).
[SkyGrid.jar](https://github.com/DavidS-Repo/SkyGridx/blob/main/SkyGrid.jar) there is only one version now since height is adjustable with the settings file.

**Comment by CorentinStauder** [comment]
Thanks for your update.

It seems on my configuration this problem is not solved, I tried removing all world and plugin folder, but I didn't go with configuration hell with velocity.

I run paper-1.20.1-49 with velocity-3.3.0-SNAPSHOT-377

I tried the last plugin version you mentioned without velocity on a fresh new server folder and it works properly with the same hardware.

This is really not a big deal as the /regen command works great and this bug is only affecting the spawn region on first initialisation.

Another strange thing is for me in the end dimension, the chunks not generating have a "L" shape. (0,0 point is at the bottom right corner on the screenshot)

![2024-05-21_15 52 46](https://github.com/DavidS-Repo/SkyGridx/assets/27969568/9636a465-7221-4cd8-bbfb-6ac6b5a791db)

Hope this can help you, but again this bug is really not affecting me and maybe is because of bad configuration on my side.

**Comment by DavidS-Repo** [comment]
Thank you for sharing the details.

I'll investigate to see if there might be any configuration issues causing the problem. If nothing stands out, I'll proceed with implementing a more robust check. This will involve a comprehensive examination of each chunk post-initial generation during the server's first boot to ensure that any improperly generated chunks are rectified. I'll aim to include it in the next update (Wednesday 5-22-2024).

Thanks again for bringing this to my attention.

**Comment by DavidS-Repo** [comment]
I've implemented an additional safety check to address the issue. Although I couldn't replicate the problem on my end, I'm hopeful that this measure will help resolve it. You can now try out the new beta version available on our GitHub page.

The updated version of the jar is available in the [main page](https://github.com/DavidS-Repo/SkyGridx).
[SkyGrid.jar](https://github.com/DavidS-Repo/SkyGridx/blob/main/SkyGrid.jar) or here directly.

Please give it a try and let me know if the issue persists. 
Thanks again for your patience :)

**Comment by CorentinStauder** [comment]
Working !
But it seems your delayed login and the message "Please wait a couple seconds while we force load spawn chunks to ensure proper generation" are launching only when my world skygrid block configuration is missing and not when my world folder is missing

**Comment by DavidS-Repo** [comment]
Hello @CorentinStauder,

I initially designed the plugin to simplify the setup process by using the presence of a specific file (SkygridBlocks/world.txt) to determine the first boot. This approach was chosen assuming most users would install the plugin and proceed with minimal configuration.

However, I understand your concerns. I'll expand the first boot check to include a more comprehensive verification, such as checking all files in the plugin folder and potentially identifying any world folders created by the server. This should improve the robustness of the initial setup process.

I'll try to include this in the beta update I am releasing at the end of today or in the next public update.
